# Generated by Django 3.0.2 on 2020-04-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('cno', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('timeing', models.CharField(max_length=30)),
                ('photo1', models.ImageField(upload_to='student/')),
                ('photo2', models.ImageField(upload_to='studnet/')),
                ('t_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
