# Generated by Django 3.0.2 on 2020-04-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='timeing',
            field=models.CharField(choices=[('9am', '9am'), ('11am', '11am')], default='9am', max_length=6),
        ),
    ]
